### ISSUE TITLE
AFO has PURLs for each version 

### ISSUE THREAD

**Issue by StroemPhi** [nfdi4cat/Ontology-Overview-of-NFDI4Cat#17]
A new version of AFO is released every 3 month an can be accessed via a PURL, e.g.
http://purl.allotrope.org/voc/afo/merged/REC/2023/09/merged-without-qudt-and-inferred.ttl for the most recent one.
To get the most latest version this PURL would have to be updated, so the next version will be:
http://purl.allotrope.org/voc/afo/merged/REC/2023/12/merged-without-qudt-and-inferred.ttl.

Maybe this helps to not have to mirror it in this repo?

**Comment by AleSteB** [comment]
Thank you! Resolved by commit 479570b
