### ISSUE TITLE
CHEMINF org website update

### ISSUE THREAD

**Issue by egonw** [nfdi4cat/Ontology-Overview-of-NFDI4Cat#19]
It should be https://github.com/semanticchemistry/semanticchemistry

For https://github.com/nfdi4cat/Ontology-Overview-of-NFDI4Cat/blob/jcheminf/ontology_metadata/CHEMINF.md

**Comment by AleSteB** [comment]
Fixed by commit 72360da41368446e4967214d8658da25f7595436
