### ISSUE TITLE
Wrong Formating of Tabels in section Ontology Modeling and Availabillity

### ISSUE THREAD

**Issue by HendrikBorgelt** [nfdi4cat/Ontology-Overview-of-NFDI4Cat#5]
In the Rex Ontology the Section "Ontology Modeling and Availabillity" has a Table entry Licence which has the Value Resonable with. I think there is a fault in the conversion from Excel Master Table to Markdown file

## Ontology Modeling And Availability
|Aspect |Description| 
 |:---|:---|
| ... | ... |
| License | Reasonable with |

**Comment by HendrikBorgelt** [comment]
I Checked the Licence in the Master Table, it is given as NaN which might be the cause of the Problem. 

[master_table/MT_OntoWorldMap_2023-08-07.xlsx](https://github.com/nfdi4cat/Ontology-Overview-of-NFDI4Cat/blob/aa6dc49efb76e98c60e034171236e460f1bbd5fc/master_table/MT_OntoWorldMap_2023-08-07.xlsx)

**Comment by AleSteB** [comment]
Thank you, I replaced the "NaN" occurences in the Mastertable with "-" and executed convert.run() again, now solved with commit f3532b15ed5c4d1382ca741e789750d3c0506ae9 that contains the fixed output (markdown-files) and the latest version of the master table "MT_OntoWorldMap_2023-09-04.xlsx"
