### ISSUE TITLE
Add OEO ontology to map?

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/Ontology-Overview-of-NFDI4Cat#6]
The Open Energy Ontology (OEO) is an actively developed domain ontology for the field of energy system modelling. https://github.com/OpenEnergyPlatform/ontology

**Comment by AleSteB** [comment]
Commit c97b83c7bd2d4756f9fc6ad56db2e8a357a8112a addresses this issue. The OEO ontology was added into the collection.
