### ISSUE TITLE
Better Markdown Syntax

### ISSUE THREAD

**Issue by HendrikBorgelt** [nfdi4cat/Ontology-Overview-of-NFDI4Cat#9]
While GitHub can interprete Markdown with no blank line after a header (###, ##, #) most Markdown tools prefer a blank line after it. Adding a blank line also should not generate any new issues as the Markdown interpreter auto chooses how much blank space is required.
Therefore we should add a further "/n" in [here](https://github.com/nfdi4cat/Ontology-Overview-of-NFDI4Cat/blob/c27101d0a19bb4e0b86dc01e31d8506c6347d7cf/convert.py#L48) at the end, [here](https://github.com/nfdi4cat/Ontology-Overview-of-NFDI4Cat/blob/c27101d0a19bb4e0b86dc01e31d8506c6347d7cf/convert.py#L52C24-L52C24) after the "## Radarplot" and after the .svg file and [here](https://github.com/nfdi4cat/Ontology-Overview-of-NFDI4Cat/blob/c27101d0a19bb4e0b86dc01e31d8506c6347d7cf/convert.py#L58).

**Comment by AleSteB** [comment]
Should be fixed by Commit 74924c320f2da02dcc57ea568aa5c175606c09af @HendrikBorgelt could you please verify?

**Comment by HendrikBorgelt** [comment]
Yes, the syntax errors were successfully fixed.
